In [13]:
import pandas as pd 
import seaborn as sns   

In [14]:
from sklearn import datasets

In [15]:
iris = datasets.load_iris()

In [16]:
# from sklearn.datasets import make_classification
# X, y = make_classification(n_samples=1000, n_features=20, n_classes=2)


In [29]:
df = pd.DataFrame(data = iris.data, columns= iris.feature_names)

In [30]:
# df['target'] = iris.target
# df['target'].unique()

In [31]:
y = iris.target

In [36]:
X = df.to_numpy()
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [37]:
import torch 
from torch.utils.data import TensorDataset

In [38]:
dataset = TensorDataset(torch.tensor(X),torch.tensor(y))

#access an individual sample
input_sample, label_sample = dataset[0]
print('input_sample:', input_sample)
print('label_sample:', label_sample)

input_sample: tensor([5.1000, 3.5000, 1.4000, 0.2000], dtype=torch.float64)
label_sample: tensor(0)


Once we create dataset using tensor.Datasets we use data loader for efficient data loading during training  

In [40]:
from torch.utils.data import DataLoader 

batch_size =2      # how many samples are included in each iterations, batching help multiple samples at once
shuffle = True     # help shuffle data after each epoch helping generalization of models


epoch: one full pass through the training dataloader 
generalization: model performs well with unseen data.

In [41]:
#create a data loader
dataloader = DataLoader(dataset, batch_size, shuffle)

iteration over data loader 

In [ ]:
for batch_input, batch_labels in dataloader :   #realtime generally batch_size > 32 for computational efficiency
    print('batch_input', batch_input)
    print('batch_labels', batch_labels)
    

batch_input tensor([[5.4000, 3.9000, 1.3000, 0.4000],
        [4.6000, 3.6000, 1.0000, 0.2000]], dtype=torch.float64)
batch_labels tensor([0, 0])
batch_input tensor([[6.1000, 3.0000, 4.6000, 1.4000],
        [7.0000, 3.2000, 4.7000, 1.4000]], dtype=torch.float64)
batch_labels tensor([1, 1])
batch_input tensor([[6.4000, 2.8000, 5.6000, 2.1000],
        [6.4000, 3.1000, 5.5000, 1.8000]], dtype=torch.float64)
batch_labels tensor([2, 2])
batch_input tensor([[5.2000, 3.5000, 1.5000, 0.2000],
        [6.3000, 2.7000, 4.9000, 1.8000]], dtype=torch.float64)
batch_labels tensor([0, 2])
batch_input tensor([[6.4000, 2.8000, 5.6000, 2.2000],
        [4.8000, 3.0000, 1.4000, 0.1000]], dtype=torch.float64)
batch_labels tensor([2, 0])
batch_input tensor([[6.2000, 2.8000, 4.8000, 1.8000],
        [6.7000, 2.5000, 5.8000, 1.8000]], dtype=torch.float64)
batch_labels tensor([2, 2])
batch_input tensor([[5.0000, 2.3000, 3.3000, 1.0000],
        [6.7000, 3.1000, 5.6000, 2.4000]], dtype=torch.float64)
batch_