In [2]:
import pandas as pd 
import seaborn as sns   

In [3]:
from sklearn import datasets

In [4]:
iris = datasets.load_iris()

In [5]:
# from sklearn.datasets import make_classification
# X, y = make_classification(n_samples=1000, n_features=20, n_classes=2)


In [6]:
df = pd.DataFrame(data = iris.data, columns= iris.feature_names)

In [7]:
# df['target'] = iris.target
# df['target'].unique()

In [8]:
y = iris.target

In [9]:
X = df.to_numpy()
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [10]:
import torch 
from torch.utils.data import TensorDataset

In [11]:
dataset = TensorDataset(torch.tensor(X),torch.tensor(y))

#access an individual sample
input_sample, label_sample = dataset[0]
print('input_sample:', input_sample)
print('label_sample:', label_sample)

input_sample: tensor([5.1000, 3.5000, 1.4000, 0.2000], dtype=torch.float64)
label_sample: tensor(0)


Once we create dataset using tensor.Datasets we use data loader for efficient data loading during training  

In [12]:
from torch.utils.data import DataLoader 

batch_size =2      # how many samples are included in each iterations, batching help multiple samples at once
shuffle = True     # help shuffle data after each epoch helping generalization of models


epoch: one full pass through the training dataloader 
generalization: model performs well with unseen data.

In [13]:
#create a data loader
dataloader = DataLoader(dataset, batch_size, shuffle)

iteration over data loader 

In [14]:
for batch_input, batch_labels in dataloader :   #realtime generally batch_size > 32 for computational efficiency
    print('batch_input', batch_input)
    print('batch_labels', batch_labels)
    

batch_input tensor([[5.5000, 2.6000, 4.4000, 1.2000],
        [5.1000, 3.4000, 1.5000, 0.2000]], dtype=torch.float64)
batch_labels tensor([1, 0])
batch_input tensor([[5.0000, 3.0000, 1.6000, 0.2000],
        [5.9000, 3.0000, 4.2000, 1.5000]], dtype=torch.float64)
batch_labels tensor([0, 1])
batch_input tensor([[6.8000, 3.2000, 5.9000, 2.3000],
        [5.5000, 4.2000, 1.4000, 0.2000]], dtype=torch.float64)
batch_labels tensor([2, 0])
batch_input tensor([[6.2000, 2.2000, 4.5000, 1.5000],
        [4.7000, 3.2000, 1.3000, 0.2000]], dtype=torch.float64)
batch_labels tensor([1, 0])
batch_input tensor([[6.9000, 3.1000, 4.9000, 1.5000],
        [7.7000, 2.8000, 6.7000, 2.0000]], dtype=torch.float64)
batch_labels tensor([1, 2])
batch_input tensor([[5.1000, 3.5000, 1.4000, 0.3000],
        [4.4000, 3.0000, 1.3000, 0.2000]], dtype=torch.float64)
batch_labels tensor([0, 0])
batch_input tensor([[7.3000, 2.9000, 6.3000, 1.8000],
        [6.1000, 2.8000, 4.7000, 1.2000]], dtype=torch.float64)
batch_

In [15]:
import numpy as np

x= np.arange(24).reshape(2,3,4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [16]:
help(dataloader)

Help on DataLoader in module torch.utils.data.dataloader object:

class DataLoader(typing.Generic)
 |  DataLoader(dataset: 'Dataset[_T_co]', batch_size: 'Optional[int]' = 1, shuffle: 'Optional[bool]' = None, sampler: 'Union[Sampler, Iterable, None]' = None, batch_sampler: 'Union[Sampler[list], Iterable[list], None]' = None, num_workers: 'int' = 0, collate_fn: 'Optional[_collate_fn_t]' = None, pin_memory: 'bool' = False, drop_last: 'bool' = False, timeout: 'float' = 0, worker_init_fn: 'Optional[_worker_init_fn_t]' = None, multiprocessing_context=None, generator=None, *, prefetch_factor: 'Optional[int]' = None, persistent_workers: 'bool' = False, pin_memory_device: 'str' = '', in_order: 'bool' = True) -> 'None'
 |
 |  Data loader combines a dataset and a sampler, and provides an iterable over the given dataset.
 |
 |  The :class:`~torch.utils.data.DataLoader` supports both map-style and
 |  iterable-style datasets with single- or multi-process loading, customizing
 |  loading order and o

In [17]:
help(TensorDataset)

Help on class TensorDataset in module torch.utils.data.dataset:

class TensorDataset(Dataset)
 |  TensorDataset(*tensors: torch.Tensor) -> None
 |
 |  Dataset wrapping tensors.
 |
 |  Each sample will be retrieved by indexing tensors along the first dimension.
 |
 |  Args:
 |      *tensors (Tensor): tensors that have the same size of the first dimension.
 |
 |  Method resolution order:
 |      TensorDataset
 |      Dataset
 |      typing.Generic
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __getitem__(self, index)
 |
 |  __init__(self, *tensors: torch.Tensor) -> None
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __len__(self)
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __annotations__ = {'tensors': tuple[torch.Tensor, ...]}
 |
 |  __orig_bases__ = (torch.utils.data.dataset.Dataset[tuple[torch.Tensor,...
 |
 |  __parameters__ = ()
 |
 |  -------------------

In [18]:
from torch import nn
import torch.optim as optim 
  

In [ ]:
#define a nn 

model = nn.Sequential(nn.Linear(in_features=4, out_features= 4),
                      nn.LeakyReLU(),
                      nn.Linear(in_features=4, out_features=3),
                      nn.LeakyReLU(),
                      nn.Linear(in_features=3, out_features=2),
                      nn.LeakyReLU(),
                      nn.Linear(in_features=2, out_features=3),             # iris dataset has 3 clases
                    #   nn.Softmax())                                        # dont need this as pytorch crossentropy loss expects a logits and has builtin softmax 

criterion = nn.CrossEntropyLoss()                #not MSELoss
optimizer = optim.SGD(model.parameters(), lr = 0.0001)

In [ ]:
num_epochs = 45


for epoch in range(num_epochs):
    for data in dataloader:
        optimizer.zero_grad()
        feature, target = data 
        pred = model(feature.float())
        loss = criterion(pred, target.long())
        loss.backward()
        optimizer.step()

/home/prabin_linux/ai/pytorch_phase1/venv_torch/lib/python3.12/site-packages/torch/nn/modules/module.py:1773: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)
/home/prabin_linux/ai/pytorch_phase1/venv_torch/lib/python3.12/site-packages/torch/nn/modules/loss.py:616: UserWarning: Using a target size (torch.Size([2])) that is different to the input size (torch.Size([2, 4])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1